# Generated by Django 3.2 on 2021-06-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='word',
            field=models.CharField(max_length=5000),
        ),
    ]
